# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  SimpleHttpServer_config = debug

else ifeq ($(config),release)
  SimpleHttpServer_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := SimpleHttpServer

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

SimpleHttpServer:
ifneq (,$(SimpleHttpServer_config))
	@echo "==== Building SimpleHttpServer ($(SimpleHttpServer_config)) ===="
	@${MAKE} --no-print-directory -C . -f SimpleHttpServer.make config=$(SimpleHttpServer_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f SimpleHttpServer.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   SimpleHttpServer"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"